### ISSUE TITLE
Correction of HY/CFOSAT Satellite Wind barbs Direction

### ISSUE THREAD

**Issue by MengXin001** [Dapiya/HY-CFOSAT-L2B-Wind-Data-Plotter#4]
## Problem 

- When using HY/CFOSAT data, the wind barbs direction will appear similar to "inverted" error which is not caused by the instrument

---
### Comparison with ASCAT
![CFOSAT](https://user-images.githubusercontent.com/54111871/139523959-49bb9de0-2b1e-41e2-b637-6292aeb39b8d.png)
![ascat_20211010_004800_metopb_47016_eps_o_coa_3202_ovw](https://user-images.githubusercontent.com/54111871/139524059-2e313540-2894-478d-96c9-dc2fcc7eb661.png)

**Comment by BigShuiTai** [comment]
> 
> ## Problem
> 
>     * When using HY/CFOSAT data, the wind barbs direction will appear similar to "inverted" error which is not caused by the instrument
> 
> 
> ### Comparison with ASCAT
> 
> ![CFOSAT](https://user-images.githubusercontent.com/54111871/139523959-49bb9de0-2b1e-41e2-b637-6292aeb39b8d.png) ![ascat_20211010_004800_metopb_47016_eps_o_coa_3202_ovw](https://user-images.githubusercontent.com/54111871/139524059-2e313540-2894-478d-96c9-dc2fcc7eb661.png)
This problem has been solved. Using variables ```wind_speed_selection``` and ```wind_dir_selection``` is the correct way.
![CFO_EXPR_SCA_C_L2B_OR_20210723T100441_15127_125_33_owv](https://user-images.githubusercontent.com/79071461/139540750-33c0687b-889e-4dbb-8ba3-54f3babd4c76.png)
